### ISSUE TITLE
First line of the board unreadable

### ISSUE THREAD

**Issue by baruchel** [mattcanty/lichess-cli#8] opened 2022-04-14 12:38 UTC
Just compiled and configured the game with no issue at all. First `lichess-cli games` however resulted in displaying my single current game with everything fine except the very first line of the board containing 13 cells (instead of 8) making the game unplayable.

![Capture d’écran_2022-04-14_14-32-26](https://user-images.githubusercontent.com/6763978/163392019-74ae640a-5758-47e1-9c96-89bce81bd8f2.png)

**Comment by mattcanty** [comment] 2022-05-22 19:34
@baruchel, this is now fixed.

It was caused by a change in the FEN being received from the Lichess API. The code was expecting just positions:
```
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR
````
but was receiving the additional game metadata
```
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
```

Have another go and hopefully it works nicely for you now!

**Closed by mattcanty** 2022-05-22 19:34 UTC
